Repository snack-exercise/snack-exercise-server, pull requests merged in 2023-07, with the labels that each got.

#9 [CI/CD] CI / CD 구성
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .gitignore
  Dockerfile
  appspec.yml
  run.sh
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌎 CI/CD, 🔮 진서 🔮

#26 [Feature] AWS Health Check 성공을 위한 컨트롤러 추가
  src/main/java/com/soma/snackexercise/controller/HealthController.java
Labels: 🌎 CI/CD, 🐥 민정 🐥

#29 [Feature] OAuth2.0 및 Security 인증 구현
  build.gradle
  src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java
  src/main/java/com/soma/snackexercise/auth/jwt/util/PasswordUtil.java
  src/main/java/com/soma/snackexercise/auth/oauth/CustomOAuth2User.java
  src/main/java/com/soma/snackexercise/auth/oauth/OAuthAttributes.java
  src/main/java/com/soma/snackexercise/auth/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/soma/snackexercise/auth/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/soma/snackexercise/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/soma/snackexercise/auth/oauth/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/soma/snackexercise/auth/oauth/userinfo/OAuth2UserInfo.java
  src/main/java/com/soma/snackexercise/config/RedisConfig.java
  src/main/java/com/soma/snackexercise/config/SecurityConfig.java
  src/main/java/com/soma/snackexercise/controller/member/MemberController.java
  src/main/java/com/soma/snackexercise/domain/member/Member.java
  src/main/java/com/soma/snackexercise/exception/MemberNotFoundException.java
  src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java
  src/main/java/com/soma/snackexercise/service/member/MemberService.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature, ⚙️ Setting, 🔮 진서 🔮

#31 [Fix] dev-deploy 배포 파일 수정
  .github/workflows/dev-deploy.yml
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: 🔮 Fix, 🌎 CI/CD, 🐥 민정 🐥

#32 [Fix] dev-deploy 배포 파이프라인 수정
  src/main/resources/application-local.yml
Labels: 🔮 Fix, 🌎 CI/CD, 🐥 민정 🐥

#37 [Feature] Jacoco 의존성 추가
  build.gradle
Labels: ✨ Feature, 🔮 진서 🔮

#41 [Feature] 운동 그룹 생성 구현
  src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
  src/main/java/com/soma/snackexercise/domain/exgroup/CreateExgroupCode.java
  src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java
  src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java
  src/main/java/com/soma/snackexercise/domain/joinlist/JoinType.java
  src/main/java/com/soma/snackexercise/dto/exgroup/PostCreateExgroupRequest.java
  src/main/java/com/soma/snackexercise/dto/exgroup/PostCreateExgroupResponse.java
  src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java
  src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java
  src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java
  src/main/java/com/soma/snackexercise/util/response/Failure.java
  src/main/java/com/soma/snackexercise/util/response/Success.java
Labels: ✨ Feature, 🐥 민정 🐥

#44 [Refactor] ErrorCode Enum에서 code, message 관리
  src/main/java/com/soma/snackexercise/advice/ErrorCode.java
  src/main/java/com/soma/snackexercise/util/response/Response.java
Labels: 🛠️ Refactoring, 🐥 민정 🐥

#46 [Fix] 운동 그룹 조회 실패 에러 클래스 생성
  src/main/java/com/soma/snackexercise/exception/ExgroupNotFoundException.java
Labels: ✨ Feature, 🔮 Fix, 🐥 민정 🐥

#47 [Feature] 추가 회원가입 및 검증 로직 추가
  src/main/java/com/soma/snackexercise/advice/ErrorCode.java
  src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java
  src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/soma/snackexercise/auth/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java
  src/main/java/com/soma/snackexercise/config/SecurityConfig.java
  src/main/java/com/soma/snackexercise/controller/auth/AuthController.java
  src/main/java/com/soma/snackexercise/controller/signup/SignupController.java
  src/main/java/com/soma/snackexercise/domain/member/Member.java
  src/main/java/com/soma/snackexercise/dto/signup/SignupRequest.java
  src/main/java/com/soma/snackexercise/exception/ExpiredJwtException.java
  src/main/java/com/soma/snackexercise/exception/InvalidRefreshTokenException.java
  src/main/java/com/soma/snackexercise/exception/MemberNameAlreadyExistsException.java
  src/main/java/com/soma/snackexercise/exception/UnauthorizedException.java
  src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java
  src/main/java/com/soma/snackexercise/service/auth/AuthService.java
  src/main/java/com/soma/snackexercise/service/signup/SignupService.java
  src/main/java/com/soma/snackexercise/util/RedisUtil.java
Labels: ✨ Feature, 🔮 진서 🔮

#52 [Refactor] BaseEntity를 사용한 리팩토링
  src/main/java/com/soma/snackexercise/domain/BaseEntity.java
  src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java
  src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java
  src/main/java/com/soma/snackexercise/domain/member/Member.java
Labels: 🛠️ Refactoring, 🐥 민정 🐥

#54 [Feature] Swagger 적용
  build.gradle
  src/main/java/com/soma/snackexercise/config/SecurityConfig.java
  src/main/java/com/soma/snackexercise/config/SwaggerConfig.java
  src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
Labels: 🐥 민정 🐥

#56 [Feature] 하나의 그룹에 속한 모든 회원 조회 기능 구현
  src/main/java/com/soma/snackexercise/config/SecurityConfig.java
  src/main/java/com/soma/snackexercise/controller/member/MemberController.java
  src/main/java/com/soma/snackexercise/domain/member/Member.java
  src/main/java/com/soma/snackexercise/dto/member/JoinListMemberDto.java
  src/main/java/com/soma/snackexercise/dto/member/response/GetOneGroupMemberResponse.java
  src/main/java/com/soma/snackexercise/repository/member/MemberRepository.java
  src/main/java/com/soma/snackexercise/service/member/MemberService.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: ✨ Feature, 🐥 민정 🐥

#58 [Fix] data.sql 실행이 hibernate가 스키마 생성한 뒤에 실행되도록 수정
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: 🔮 Fix, 🐥 민정 🐥

#59 [Fix] swagger cors 에러 해결
  src/main/java/com/soma/snackexercise/SnackExerciseApplication.java
Labels: 🔮 Fix, 🐥 민정 🐥

#61 fix : CORS 에러 해결
  src/main/java/com/soma/snackexercise/config/WebConfig.java
Labels: 🔮 Fix, 🐥 민정 🐥

#62 [Feature] Exercise Entity, Repository 클래스 생성
  src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java
  src/main/java/com/soma/snackexercise/domain/exercise/ExerciseCategory.java
  src/main/java/com/soma/snackexercise/repository/exercise/ExerciseRepository.java
Labels: ✨ Feature, 🐥 민정 🐥

#64 [Fix]: Enum이 String 데이터 형식으로 저장되도록 수정
  src/main/java/com/soma/snackexercise/domain/exercise/Exercise.java
Labels: 🐥 민정 🐥

#65 [Feature] 당일 릴레이미션 수행 현황 정보 조회 기능
  src/main/java/com/soma/snackexercise/controller/mission/MissionController.java
  src/main/java/com/soma/snackexercise/domain/mission/Mission.java
  src/main/java/com/soma/snackexercise/dto/mission/response/MemberMissionDto.java
  src/main/java/com/soma/snackexercise/dto/mission/response/TodayMissionCurrentResultDto.java
  src/main/java/com/soma/snackexercise/repository/mission/MisssionRepository.java
  src/main/java/com/soma/snackexercise/service/mission/MissionService.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: ✨ Feature, 🐥 민정 🐥

#69 [Refactor] Jwt 인증 인가 로직 리팩토링
  src/main/java/com/soma/snackexercise/advice/ErrorCode.java
  src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java
  src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/soma/snackexercise/auth/jwt/service/JwtService.java
  src/main/java/com/soma/snackexercise/auth/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/soma/snackexercise/controller/auth/AuthController.java
  src/main/java/com/soma/snackexercise/controller/signup/SignupController.java
  src/main/java/com/soma/snackexercise/dto/auth/AccessTokenResponse.java
  src/main/java/com/soma/snackexercise/service/auth/AuthService.java
  src/main/java/com/soma/snackexercise/service/signup/SignupService.java
  src/main/java/com/soma/snackexercise/util/RedisUtil.java
Labels: 🛠️ Refactoring, 🔮 Fix, 🔮 진서 🔮

#71 [Feature] 랭킹 기능 구현
  src/main/java/com/soma/snackexercise/advice/ErrorCode.java
  src/main/java/com/soma/snackexercise/advice/ExceptionAdvice.java
  src/main/java/com/soma/snackexercise/controller/mission/MissionController.java
  src/main/java/com/soma/snackexercise/dto/mission/response/RankingResponseDto.java
  src/main/java/com/soma/snackexercise/exception/WrongRequestParamException.java
  src/main/java/com/soma/snackexercise/repository/mission/MisssionRepository.java
  src/main/java/com/soma/snackexercise/service/mission/MissionService.java
Labels: ✨ Feature, 🐥 민정 🐥

#72 [Chore] swagger에 Query Param 설명 추가
  src/main/java/com/soma/snackexercise/controller/mission/MissionController.java
Labels: 🐥 민정 🐥

#80 [Feature] 방장이 회원 강퇴 / 회원이 탈퇴 API
  src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
  src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java
  src/main/java/com/soma/snackexercise/exception/JoinListNotFoundException.java
  src/main/java/com/soma/snackexercise/exception/NotExgroupHostException.java
  src/main/java/com/soma/snackexercise/exception/NotExgroupMemberException.java
  src/main/java/com/soma/snackexercise/exception/NotHostException.java
  src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java
  src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java
  src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java
  src/main/java/com/soma/snackexercise/service/member/MemberDeletionService.java
  src/main/java/com/soma/snackexercise/service/member/MemberService.java
  src/main/java/com/soma/snackexercise/service/mission/MissionService.java
Labels: ✨ Feature, 🔮 진서 🔮

#81 [Feature] 그룹 릴레이 미션 시작 기능 구현
  src/main/java/com/soma/snackexercise/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
  src/main/java/com/soma/snackexercise/domain/exgroup/Exgroup.java
  src/main/java/com/soma/snackexercise/dto/exgroup/response/ExgroupResponse.java
  src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java
  src/main/java/com/soma/snackexercise/service/signup/SignupService.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🐥 민정 🐥

#82 [Chore] Service layer 함수명 통일, Response Dto에 toDto 함수 생성
  src/main/java/com/soma/snackexercise/controller/exgroup/ExgroupController.java
  src/main/java/com/soma/snackexercise/controller/member/MemberController.java
  src/main/java/com/soma/snackexercise/controller/mission/MissionController.java
  src/main/java/com/soma/snackexercise/dto/exgroup/request/PostCreateExgroupRequest.java
  src/main/java/com/soma/snackexercise/dto/exgroup/response/PostCreateExgroupResponse.java
  src/main/java/com/soma/snackexercise/dto/member/response/GetOneGroupMemberResponse.java
  src/main/java/com/soma/snackexercise/dto/mission/response/MemberMissionDto.java
  src/main/java/com/soma/snackexercise/dto/mission/response/RankingResponse.java
  src/main/java/com/soma/snackexercise/dto/mission/response/TodayMissionResultResponse.java
  src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java
  src/main/java/com/soma/snackexercise/service/member/MemberService.java
  src/main/java/com/soma/snackexercise/service/mission/MissionService.java
Labels: 🛀 Cleanup, 🐥 민정 🐥

#83 fix : 백엔드 서버 도메인 변경에 따른 swagger 도메인 수정(#76)
  src/main/java/com/soma/snackexercise/SnackExerciseApplication.java
Labels: 🛀 Cleanup, 🐥 민정 🐥

#87 [Fix] CORS 에러 해결
  src/main/java/com/soma/snackexercise/config/WebConfig.java
Labels: 🔮 Fix, 🐥 민정 🐥

#95 [Feature] docker-compose
  .github/workflows/dev-deploy.yml
  docker-compose.yml
Labels: 🌎 CI/CD, 🐥 민정 🐥

#99 [Feature] 그룹 시작시간에 미션 할당 기능 구현
  .github/workflows/dev-deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/soma/snackexercise/SnackExerciseApplication.java
  src/main/java/com/soma/snackexercise/config/ScheduledConfig.java
  src/main/java/com/soma/snackexercise/controller/exercise/ExerciseController.java
  src/main/java/com/soma/snackexercise/controller/notification/NotificationController.java
  src/main/java/com/soma/snackexercise/domain/joinlist/JoinList.java
  src/main/java/com/soma/snackexercise/domain/member/Member.java
  src/main/java/com/soma/snackexercise/domain/mission/Mission.java
  src/main/java/com/soma/snackexercise/domain/notification/NotificationMessage.java
  src/main/java/com/soma/snackexercise/dto/member/request/MemberUpdateFcmTokenRequest.java
  src/main/java/com/soma/snackexercise/dto/member/response/MemberUpdateFcmTokenResponse.java
  src/main/java/com/soma/snackexercise/repository/exgroup/ExgroupRepository.java
  src/main/java/com/soma/snackexercise/repository/joinlist/JoinListRepository.java
  src/main/java/com/soma/snackexercise/repository/mission/MissionRepository.java
  src/main/java/com/soma/snackexercise/service/auth/AuthService.java
  src/main/java/com/soma/snackexercise/service/exgroup/ExgroupService.java
  src/main/java/com/soma/snackexercise/service/mission/MissionSchedulerService.java
  src/main/java/com/soma/snackexercise/service/notification/FirebaseCloudMessageService.java
  src/main/java/com/soma/snackexercise/service/notification/NotificationService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature, 🐥 민정 🐥
